import { motion } from "framer-motion";
import { fadeIn } from "@/lib/motion";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useForm } from "react-hook-form";
import { Form, FormField, FormItem, FormControl, FormLabel } from "@/components/ui/form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";

const formSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
    email: z.string().email("Invalid email address"),
      message: z.string().min(10, "Message must be at least 10 characters"),
      });

      export function Contact() {
        const form = useForm<z.infer<typeof formSchema>>({
            resolver: zodResolver(formSchema),
                defaultValues: {
                      name: "",
                            email: "",
                                  message: "",
                                      },
                                        });

                                          function onSubmit(data: z.infer<typeof formSchema>) {
                                              console.log(data);
                                                }

                                                  return (
                                                      <section className="relative w-full min-h-screen mx-auto p-6">
                                                            <motion.div
                                                                    variants={fadeIn("up", "tween", 0.3, 1)}
                                                                            initial="hidden"
                                                                                    animate="show"
                                                                                          >
                                                                                                  <Card className="max-w-xl mx-auto">
                                                                                                            <CardContent className="pt-6">
                                                                                                                        <h2 className="text-3xl font-bold mb-6">Contact Me</h2>
                                                                                                                                    
                                                                                                                                                <Form {...form}>
                                                                                                                                                              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                                                                                                                                                                              <FormField
                                                                                                                                                                                                control={form.control}
                                                                                                                                                                                                                  name="name"
                                                                                                                                                                                                                                    render={({ field }) => (
                                                                                                                                                                                                                                                        <FormItem>
                                                                                                                                                                                                                                                                              <FormLabel>Name</FormLabel>
                                                                                                                                                                                                                                                                                                    <FormControl>
                                                                                                                                                                                                                                                                                                                            <Input {...field} />
                                                                                                                                                                                                                                                                                                                                                  </FormControl>
                                                                                                                                                                                                                                                                                                                                                                      </FormItem>
                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                        <FormField
                                                                                                                                                                                                                                                                                                                                                                                                                                          control={form.control}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            name="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              render={({ field }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FormItem>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <FormLabel>Email</FormLabel>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <FormControl>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Input {...field} type="email" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </FormControl>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </FormItem>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FormField
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    control={form.control}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      name="message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        render={({ field }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <FormItem>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FormLabel>Message</FormLabel>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <FormControl>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Textarea {...field} rows={5} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </FormControl>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </FormItem>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button type="submit" className="w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Send Message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      